version: '3.7'

services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong-with-aes-encryption
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      kong-database:
        condition: service_healthy
    command: kong migrations bootstrap
    restart: 'no'

  kong:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PLUGINS: bundled,aes-encryption
    ports:
      - "8000:8000"  # Proxy (HTTP)
      - "8443:8443"  # Proxy (HTTPS)
      - "8001:8001"  # Admin API (HTTP)
      - "8444:8444"  # Admin API (HTTPS)
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    restart: always

  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: kong
    ports:
      - "1337:1337"
    depends_on:
      - kong-database
      - kong
    restart: always

volumes:
  kong_db_data: